name: RushOwl ChatWoot Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -f ./Dockerfile --tag rushowl/osm-static-maps:latest .
    - name: Push the latest Docker image
      run: docker push rushowl/osm-static-maps:latest
